[tool.poetry]
name = "life-sim"
version = "0.1.0"
description = ""
authors = ["san <deadcove@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.5.2"
defaultlist = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
